site_name: Lbocms
pages:
- [index.md, Why]
- [getting_started.md, Getting Started]
- [workflow.md, Workflow]
- [cms.md, The Content Management System]
- [integration.md, Integration]
- [seo.md, SEO]
- [users.md, Users]
- [s3.md, Upload hosting]
- [licensing.md, Licensing]
- [advanced.md, Advanced Integrations]
theme: readthedocs
